name: canadoreino
description: Restaurante Sítio Cana do Reino.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  hexcolor: ^1.0.6
  url_launcher: ^5.7.10
  path_provider: ^1.6.24
  sqfentity_gen: ^1.4.0+2
  animated_text_kit: ^2.5.4
  sign_in_with_apple: ^2.5.4
  argon_buttons_flutter: ^1.0.6
  font_awesome_flutter: ^8.10.0
  flutter_cmoon_icons: ^0.1.0
  keyboard_actions: ^3.2.1+1
  flutter_spinkit: "^4.1.2"
  auto_animated: ^2.1.0
  brasil_fields: ^0.5.0
  supercharged: ^1.12.0
  splashscreen: ^1.3.5
  connectivity: ^2.0.2
  sqfentity: ^1.4.0+3
  flushbar: ^1.10.4
  provider: ^4.1.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/logo/logo.png
    - images/bgs/bg1.jpg
    - images/bgs/bg2.jpg
    - images/bgs/bg3.jpg
    - images/bgs/bg4.jpg
    - images/bgs/bg5.jpg
    - images/placeholder.png
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
